### ISSUE TITLE
Data Directory missing from the Capture Directory

### ISSUE THREAD

**Issue by Sagnik2810Sarkar** [astra-vision/MaterialPalette#3]
As explained in the Project Structure of your README, the data directory inside the capture directory holds essential files for running the complete pipeline. Since it is missing, attempts at running pipeline.py fail with the following error while importing modules:

 python pipeline.py G:\SAGNIK_Material_Palette\Material_Palette\mansion
Traceback (most recent call last):
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\pipeline.py", line 7, in <module>
    import capture
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\capture\__init__.py", line 2, in <module>
    from .utils.model import get_inference_module
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\capture\utils\__init__.py", line 3, in <module>
    from .cli import get_args
  File "G:\SAGNIK_Material_Palette\Material_Palette\MaterialPalette\capture\utils\cli.py", line 11, in <module>
    from ..data.module import DataModule
ModuleNotFoundError: No module named 'capture.data'

Is there anything on my end that can be done to solve this or is there an update slated to the repo itself that takes care of this?

**Comment by wonjunior** [comment]
Hi, thank you for notifying me. There was indeed an issue in the [`.gitignore`](https://github.com/astra-vision/MaterialPalette/blob/master/.gitignore). It should be fixed now (see [commit](https://github.com/astra-vision/MaterialPalette/commit/42e48d8c0e68b7df77a57fae87de3f901b33bd42)).
