### ISSUE TITLE
AssertionError in the infer.py script from Quick Start

### ISSUE THREAD

**Issue by v4r4rth** [astra-vision/MaterialPalette#4]
Facing this issue after downloading blue_tiles:

(matpal) issac@issac-KVM:~/MaterialPalette$ python concept/infer.py blue_tiles/unet/adapter_model.bin --outdir OUTPUT
Namespace(path=PosixPath('blue_tiles/unet/adapter_model.bin'), outdir=PosixPath('OUTPUT'), token=None, stitch_mode='wmean', resolution=1024, prompt='p1', seed=1, renorm=False, num_inference_steps=50)
Traceback (most recent call last):
  File "/home/issac/MaterialPalette/concept/infer.py", line 412, in <module>
    main(args)
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/issac/MaterialPalette/concept/infer.py", line 114, in main
    assert args.path.is_dir()
AssertionError

**Comment by wonjunior** [comment]
Hi, `args.path` (the first argument of this function) needs to be a directory! The path `"path/to/LoRA/checkpoint"` I am referring to in the [README](https://github.com/astra-vision/MaterialPalette?tab=readme-ov-file#-generation) corresponds to **the parent directory** containing both `unet/` and `text_encoder/` subfolders. 

You should instead call it as:
```
python concept/infer.py blue_tiles --outdir OUTPUT 
```

**Comment by v4r4rth** [comment]
Got this new error instead - 
```
(matpal) issac@issac-KVM:~/MaterialPalette$ python concept/infer.py blue_tiles --outdir OUTPUT 
Namespace(path=PosixPath('blue_tiles'), outdir=PosixPath('OUTPUT'), token=None, stitch_mode='wmean', resolution=1024, prompt='p1', seed=1, renorm=False, num_inference_steps=50)
loading LoRA with token azertyuiop
Traceback (most recent call last):
  File "/home/issac/MaterialPalette/concept/infer.py", line 412, in <module>
    main(args)
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/issac/MaterialPalette/concept/infer.py", line 119, in main
    pipe = get_lora_sd_pipeline(ckpt_dir=Path(args.path))
  File "/home/issac/MaterialPalette/concept/infer.py", line 77, in get_lora_sd_pipeline
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 908, in from_pretrained
    cached_folder = cls.download(
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1488, in download
    cached_folder = snapshot_download(
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/issac/miniconda3/envs/matpal/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 235, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.
(matpal) issac@issac-KVM:~/MaterialPalette$ 
```

**Comment by v4r4rth** [comment]
Fixed! Just changed these lines in the infer.py script:

```
pipe = StableDiffusionPipeline.from_pretrained(
        base_model_name_or_path,
        torch_dtype=dtype,
        local_files_only=False,
        safety_checker=None,
    ).to(device)
```
